; Tests for prover/link.ml

(executable
 (name link_tests)
 (public_name -)
 (modules link_tests)
 (libraries coq-actema.prover alcotest)
 (modes js))

(rule
 (alias runtest-js)
 (action
  (run node %{dep:link_tests.bc.js})))

; Playground

(executable
 (name playground)
 (public_name -)
 (modules playground)
 (libraries coq-actema.prover)
 (modes js))

(rule
 (alias playground)
 (action
  (run node %{dep:playground.bc.js})))
