.PHONY: all test clean build

all: build

# Build everything (except the frontend, which you should launch via npm run electron:serve).
build:
	dune build
# Install the dune stuff. This is required to be able to step
# through coq files using VScode/coqtop.
	dune install
# Copy the file generated by js_of_ocaml to the frontend.
	cp -f _build/default/prover/js/jsprover.js frontend/public/prover.js

test: build
# Run the regular Ocaml tests.
	dune runtest -f
# Run the Ocaml tests that use Js_of_ocaml.
	dune build @runtest-js -f

clean:
	dune clean