lib: [
  "_build/install/default/lib/prover/META"
  "_build/install/default/lib/prover/dune-package"
  "_build/install/default/lib/prover/engine/engine.a" {"engine/engine.a"}
  "_build/install/default/lib/prover/engine/engine.cma" {"engine/engine.cma"}
  "_build/install/default/lib/prover/engine/engine.cmi" {"engine/engine.cmi"}
  "_build/install/default/lib/prover/engine/engine.cmt" {"engine/engine.cmt"}
  "_build/install/default/lib/prover/engine/engine.cmx" {"engine/engine.cmx"}
  "_build/install/default/lib/prover/engine/engine.cmxa" {"engine/engine.cmxa"}
  "_build/install/default/lib/prover/engine/engine.cmxs" {"engine/engine.cmxs"}
  "_build/install/default/lib/prover/engine/engine.ml" {"engine/engine.ml"}
  "_build/install/default/lib/prover/engine/engine__Fo.cmi" {"engine/engine__Fo.cmi"}
  "_build/install/default/lib/prover/engine/engine__Fo.cmt" {"engine/engine__Fo.cmt"}
  "_build/install/default/lib/prover/engine/engine__Fo.cmx" {"engine/engine__Fo.cmx"}
  "_build/install/default/lib/prover/engine/engine__Io.cmi" {"engine/engine__Io.cmi"}
  "_build/install/default/lib/prover/engine/engine__Io.cmt" {"engine/engine__Io.cmt"}
  "_build/install/default/lib/prover/engine/engine__Io.cmti" {"engine/engine__Io.cmti"}
  "_build/install/default/lib/prover/engine/engine__Io.cmx" {"engine/engine__Io.cmx"}
  "_build/install/default/lib/prover/engine/engine__Jsapi.cmi" {"engine/engine__Jsapi.cmi"}
  "_build/install/default/lib/prover/engine/engine__Jsapi.cmt" {"engine/engine__Jsapi.cmt"}
  "_build/install/default/lib/prover/engine/engine__Jsapi.cmx" {"engine/engine__Jsapi.cmx"}
  "_build/install/default/lib/prover/engine/engine__Lexer.cmi" {"engine/engine__Lexer.cmi"}
  "_build/install/default/lib/prover/engine/engine__Lexer.cmt" {"engine/engine__Lexer.cmt"}
  "_build/install/default/lib/prover/engine/engine__Lexer.cmx" {"engine/engine__Lexer.cmx"}
  "_build/install/default/lib/prover/engine/engine__Location.cmi" {"engine/engine__Location.cmi"}
  "_build/install/default/lib/prover/engine/engine__Location.cmt" {"engine/engine__Location.cmt"}
  "_build/install/default/lib/prover/engine/engine__Location.cmti" {"engine/engine__Location.cmti"}
  "_build/install/default/lib/prover/engine/engine__Location.cmx" {"engine/engine__Location.cmx"}
  "_build/install/default/lib/prover/engine/engine__Parser.cmi" {"engine/engine__Parser.cmi"}
  "_build/install/default/lib/prover/engine/engine__Parser.cmt" {"engine/engine__Parser.cmt"}
  "_build/install/default/lib/prover/engine/engine__Parser.cmti" {"engine/engine__Parser.cmti"}
  "_build/install/default/lib/prover/engine/engine__Parser.cmx" {"engine/engine__Parser.cmx"}
  "_build/install/default/lib/prover/engine/engine__Proof.cmi" {"engine/engine__Proof.cmi"}
  "_build/install/default/lib/prover/engine/engine__Proof.cmt" {"engine/engine__Proof.cmt"}
  "_build/install/default/lib/prover/engine/engine__Proof.cmx" {"engine/engine__Proof.cmx"}
  "_build/install/default/lib/prover/engine/engine__Syntax.cmi" {"engine/engine__Syntax.cmi"}
  "_build/install/default/lib/prover/engine/engine__Syntax.cmt" {"engine/engine__Syntax.cmt"}
  "_build/install/default/lib/prover/engine/engine__Syntax.cmx" {"engine/engine__Syntax.cmx"}
  "_build/install/default/lib/prover/engine/engine__Utils.cmi" {"engine/engine__Utils.cmi"}
  "_build/install/default/lib/prover/engine/engine__Utils.cmt" {"engine/engine__Utils.cmt"}
  "_build/install/default/lib/prover/engine/engine__Utils.cmx" {"engine/engine__Utils.cmx"}
  "_build/install/default/lib/prover/engine/fo.ml" {"engine/fo.ml"}
  "_build/install/default/lib/prover/engine/io.ml" {"engine/io.ml"}
  "_build/install/default/lib/prover/engine/io.mli" {"engine/io.mli"}
  "_build/install/default/lib/prover/engine/jsapi.ml" {"engine/jsapi.ml"}
  "_build/install/default/lib/prover/engine/lexer.ml" {"engine/lexer.ml"}
  "_build/install/default/lib/prover/engine/location.ml" {"engine/location.ml"}
  "_build/install/default/lib/prover/engine/location.mli" {"engine/location.mli"}
  "_build/install/default/lib/prover/engine/parser.ml" {"engine/parser.ml"}
  "_build/install/default/lib/prover/engine/parser.mli" {"engine/parser.mli"}
  "_build/install/default/lib/prover/engine/proof.ml" {"engine/proof.ml"}
  "_build/install/default/lib/prover/engine/syntax.ml" {"engine/syntax.ml"}
  "_build/install/default/lib/prover/engine/utils.ml" {"engine/utils.ml"}
  "_build/install/default/lib/prover/opam"
]
bin: [
  "_build/install/default/bin/prover"
]
