image: ocaml/opam2:4.08

variables:
  OPAMYES: "yes"
  OPAMVERBOSE: 1

services:
- docker:dind

.tests:
  script:
  - opam config list
  - opam update
  - opam pin add -n .
  - opam install depext
  - opam depext prover
  - opam install --deps-only prover
  - make

default:
  extends: .tests
